services:
  # SEU SERVIÇO EXISTENTE (sem alterações)
  step-daddy-live-hd:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        API_URL: ${API_URL}
        PROXY_CONTENT: ${PROXY_CONTENT}
        SOCKS5: ${SOCKS5}
    environment:
      - PORT=${PORT}
      - API_URL=${API_URL}
      - PROXY_CONTENT=${PROXY_CONTENT}
      - SOCKS5=${SOCKS5}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    env_file:
      - .env

  # SERVIÇO 'gerador-live' ATUALIZADO COM AS NOVAS INFORMAÇÕES
  gerador-live:
    image: gerador-m3u-live
    container_name: live
    restart: always  # Traduzido do --restart always
    ports:
      - "8007:8007"
    environment:
      # Puxa a variável GITHUB_TOKEN do arquivo .env
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      # Define o Timezone diretamente
      - TZ=America/Sao_Paulo
    env_file:
      # Aponta para o mesmo arquivo .env que o outro serviço usa
      - .env