services:
  # Serviço do PROXY (com a sintaxe de 'args' corrigida)
  step-daddy-live-hd:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile
      # 'args' agora está DENTRO da seção 'build'
      args:
        PORT: ${PORT}
        API_URL: ${API_URL}
        PROXY_CONTENT: ${PROXY_CONTENT}
        SOCKS5: ${SOCKS5}
    environment:
      - PORT=${PORT}
      - API_URL=${API_URL}
      - PROXY_CONTENT=${PROXY_CONTENT}
      - SOCKS5=${SOCKS5}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    env_file:
      - .env

  # Serviço do GERADOR (já estava correto)
  gerador-live:
    container_name: live
    build: ./schedule
    restart: always
    ports:
      - "8007:8007"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TZ=America/Sao_Paulo
    env_file:
      - .env